#!/usr/bin/env bash
# Script to run MININAV2D from a Euroc rosbag data source.
# Usage: tutorial_euroc <output save folder> <rosbag path> [<additional mininav2d flags>]

REST=$@

export HEAR_SLAM_ROOT_CFG="$OPENVINS_CONFIG_DIR/hear_slam_root_cfg.yaml"

rosrun mininav2d mininav2d \
  --alsologtostderr=1 \
  --v=2  $REST
