#!/usr/bin/env bash
# Script to run OPENVINSLI from a Euroc rosbag data source with localization enabled.
# Usage: tutorial_euroc <localization map path> <output save folder> <rosbag path> [<additional openvinsli flags>]

LOCALIZATION_MAP_INPUT=$1
LOCALIZATION_MAP_OUTPUT=$2
ROSBAG=$3
NCAMERA_CALIBRATION="$OPENVINS_CONFIG_DIR/ncamera-euroc.yaml"
IMU_PARAMETERS_MAPLAB="$OPENVINS_CONFIG_DIR/imu-adis16488.yaml"
REST=$@

export HEAR_SLAM_ROOT_CFG="$OPENVINS_CONFIG_DIR/hear_slam_root_cfg.yaml"

rosrun openvinsli openvinsli \
  --alsologtostderr=1 \
  --v=2 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --publish_debug_markers  \
  --datasource_type="rosbag" \
  --optimize_map_to_localization_map=false \
  --vio_localization_map_folder=$LOCALIZATION_MAP_INPUT \
  --save_map_folder=$LOCALIZATION_MAP_OUTPUT \
  --map_builder_save_image_as_resources=false \
  --datasource_rosbag=$ROSBAG $REST
