#!/usr/bin/env bash
# Script to run OPENVINSLI from a Euroc rosbag data source with localization enabled.
# Usage: tutorial_euroc <localization map path> <output save folder> <rosbag path> [<additional openvinsli flags>]

LOCALIZATION_MAP_INPUT=$1
LOCALIZATION_MAP_OUTPUT=$2
DATASET=$3

# NCAMERA_CALIBRATION="$OPENVINS_CONFIG_DIR/ncamera-hearslam.yaml"
# IMU_PARAMETERS_MAPLAB="$OPENVINS_CONFIG_DIR/imu-hearslam.yaml"
# sensor_option=" --ncamera_calibration=$NCAMERA_CALIBRATION --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB "

SENSOR_CALIBRATION="$OPENVINS_CONFIG_DIR/hearslam-stereo.yaml"
sensor_option=" --sensor_calibration_file=$SENSOR_CALIBRATION "

REST=$@

rosrun openvinsli openvinsli \
  --alsologtostderr=1 \
  --v=2 \
  $sensor_option \
  --publish_debug_markers  \
  --datasource_type="hearslam" \
  --optimize_map_to_localization_map=false \
  --vio_localization_map_folder=$LOCALIZATION_MAP_INPUT \
  --save_map_folder=$LOCALIZATION_MAP_OUTPUT \
  --map_builder_save_image_as_resources=false \
  --openvinsli_run_map_builder=false \
  --vio_max_localization_frequency_hz=2.0 \
  --datasource_hearslam=$DATASET $REST
