#!/usr/bin/env bash
# Script to run OPENVINSLI from a Euroc rosbag data source.
# Usage: tutorial_euroc <output save folder> <rosbag path> [<additional openvinsli flags>]

LOCALIZATION_MAP_OUTPUT=$1
ROSBAG=$2
NCAMERA_CALIBRATION="$OPENVINS_CONFIG_DIR/ncamera-euroc.yaml"
IMU_PARAMETERS_MAPLAB="$OPENVINS_CONFIG_DIR/imu-adis16488.yaml"
REST=$@

rosrun openvinsli openvinsli \
  --alsologtostderr=1 \
  --v=2 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --datasource_type="rosbag" \
  --save_map_folder="$LOCALIZATION_MAP_OUTPUT" \
  --optimize_map_to_localization_map=false \
  --map_builder_save_image_as_resources=false \
  --datasource_rosbag=$ROSBAG $REST
