#!/usr/bin/env bash
# Script to run ROVIOLI from a Euroc rosbag data source.
# Usage: tutorial_euroc <output save folder> <rosbag path> [<additional rovioli flags>]

LOCALIZATION_MAP_OUTPUT=$1
DATASET=$2

# NCAMERA_CALIBRATION="$ROVIO_CONFIG_DIR/ncamera-hearslam.yaml"
# IMU_PARAMETERS_MAPLAB="$ROVIO_CONFIG_DIR/imu-hearslam.yaml"
# sensor_option=" --ncamera_calibration=$NCAMERA_CALIBRATION --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB "

SENSOR_CALIBRATION="$ROVIO_CONFIG_DIR/hearslam-stereo.yaml"
sensor_option=" --sensor_calibration_file=$SENSOR_CALIBRATION "

REST=$@



rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --v=2 \
  $sensor_option \
  --datasource_type="hearslam" \
  --save_map_folder="$LOCALIZATION_MAP_OUTPUT" \
  --optimize_map_to_localization_map=false \
  --map_builder_save_image_as_resources=false \
  --datasource_hearslam=$DATASET $REST
